ota_from_target_files: add missing format specifier for log msg
The logging call at the end of ota_from_target_files.py was missing a
string format specifier ('%s'), which caused below TypeError when attempting
to log the name of the generated OTA package.

TypeError: not all arguments converted during string formatting

Bug: N/A
Test: manual run of ota_from_target_files.py

Change-Id: Id61b4a546b6371a1c35bba4c805aa70c86cbb2d5
Signed-off-by: Sandeep Dhavale <dhavale@google.com>